version: '3.8'

services:
  backend:
    build: 
      context: ./server
    ports:
      - "4567:4567"
    env_file:
      - ./server/.env
    depends_on:
      - db
    

  frontend:
    build: 
      context: ./client
    ports:
      - "3000:80"
  

  db:
    image: postgres:15
    restart: always
    environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root
        POSTGRES_DB: tazky
    volumes:
      - pgdata:/var/lib/postgresql/data
  

volumes:
  pgdata: