# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem 'sinatra'
gem 'bcrypt'


gem 'sinatra-cross_origin'

gem "rackup"
gem "puma"
gem "rack-cors"


gem 'jwt'
gem 'rack-session'
gem 'dotenv'

gem 'pg'
