# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem 'sinatra'
gem 'bcrypt'

gem 'sqlite3'

gem 'sinatra-cross_origin'

gem "rackup", "~> 2.2"
gem "puma", "~> 6.6"
gem "rack-cors"

gem 'jwt'
gem 'rack-session'
gem 'dotenv'
